apiVersion: v1
kind: Pod
metadata:
  name: mysqldatabase-pv
spec:
  containers:
  - name: mysqldatabase
    image: mysql
    volumeMounts:
    - name: mysqlvolume
      mountPath: /var/lib/mysql
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: mydatabase
      - name: MYSQL_USER
        value: user
      - name: MYSQL_PASSWORD
        value: user
  volumes:
  - name: mysqlvolume
    persistentVolumeClaim:
      claimName: myfirstvolumeclaim

