apiVersion: v1
kind: Service
metadata:
  name: my-service-nodeport
  namespace: production
spec:
  type: NodePort
  selector:
    app: web
  ports:
  - nodePort: 30008
    port: 8080
    targetPort: 8080
